[tool.pytest.ini_options]
addopts = "-vv --strict-markers -p no:cacheprovider"

[tool.mypy]
strict = true
python_version = "3.10"
mypy_path = "stubs"
cache_dir = "/dev/null"

[[tool.mypy.overrides]]
module = "sqlalchemy.*"
ignore_missing_imports = true