# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str = None, details: List[object] = None):  # noqa: E501
        """Error - a model defined in Swagger

        :param message: The message of this Error.  # noqa: E501
        :type message: str
        :param details: The details of this Error.  # noqa: E501
        :type details: List[object]
        """
        self.swagger_types = {
            'message': str,
            'details': List[object]
        }

        self.attribute_map = {
            'message': 'message',
            'details': 'details'
        }
        self._message = message
        self._details = details

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this Error.

        Error message  # noqa: E501

        :return: The message of this Error.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this Error.

        Error message  # noqa: E501

        :param message: The message of this Error.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def details(self) -> List[object]:
        """Gets the details of this Error.

        (Option) Array to supply additional detailed error information specified as name/value pairs. Values may be of any type, including objects.  # noqa: E501

        :return: The details of this Error.
        :rtype: List[object]
        """
        return self._details

    @details.setter
    def details(self, details: List[object]):
        """Sets the details of this Error.

        (Option) Array to supply additional detailed error information specified as name/value pairs. Values may be of any type, including objects.  # noqa: E501

        :param details: The details of this Error.
        :type details: List[object]
        """

        self._details = details
