name: Project Tests
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test kme with pytest
        run: pytest kme
      - name: Test qcs with pytest
        run: pytest qcs
      - name: Test kme with mypy
        run: mypy kme
      - name: Test qcs with mypy
        run: mypy qcs