name: Project Tests
on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: "Set up Poetry"
        uses: Gr1N/setup-poetry@v7
      - name: "Install dependencies"
        run: poetry install
      - name: "Set testing environment"
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
               set env=test
          else
               export env=test
          fi
        shell: bash
      - name: "Test qcs using pytest"
        run: poetry run pytest qcs
      - name: "Test qcs using mypy"
        run: poetry run mypy qcs
      - name: "Test kme using pytest"
        run: poetry run pytest kme
# Test termporary disabled, because pydantic plugin for mypy does not work.
#      - name: "Test kme using mypy"
#        run: poetry run mypy kme

