name: Project Tests
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: "Set up Poetry"
        uses: Gr1N/setup-poetry@v7
      - name: "Install dependencies"
        run: poetry install
      - name: "Test using pytest"
        run: env=test poetry run pytest
      - name: "Test using mypy"
        run: env=test poetry run mypy kme qcs